"""Add file_path and file_type to BusinessPlanTemplate

Revision ID: b59d4bcbddb4
Revises: 
Create Date: 2025-07-04 10:23:41.859123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59d4bcbddb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_plan_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('template_content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_plan_templates', schema=None) as batch_op:
        batch_op.alter_column('template_content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
